# Generated by Django 4.2.2 on 2023-07-18 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='QuickLookQuery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=240)),
                ('land_purchase_date', models.DateField()),
                ('region', models.CharField(choices=[('UK', 'UK'), ('Poland', 'Poland'), ('Germany', 'Germany'), ('US', 'US')], max_length=240)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('building_sale', models.DateField()),
                ('mass_grading_start', models.DateField()),
                ('total_area', models.FloatField()),
                ('rent_per_unit_area', models.FloatField()),
                ('exit_cap', models.FloatField()),
                ('land_cost', models.FloatField()),
                ('building_hard_cost', models.FloatField()),
                ('building_soft_cost', models.FloatField()),
                ('tenant_improvements', models.FloatField()),
                ('cash_contributions', models.FloatField()),
                ('rent_free_period', models.IntegerField()),
                ('lease_up_period', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='QuickLookResults',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unlevered_irr', models.FloatField(verbose_name='Unlevered IRR')),
                ('unlevered_mult', models.FloatField(verbose_name='Unlevered EM')),
                ('yoc', models.FloatField(verbose_name='Yield on Cost')),
                ('ncf', models.FloatField(verbose_name='Net Cash Flow')),
                ('unl_costs', models.FloatField(verbose_name='Total Unlevered Costs')),
                ('lev_costs', models.FloatField(verbose_name='Total Levered Costs')),
                ('unl_peak_equity', models.FloatField(verbose_name='Unlevered Peak Equity')),
                ('net_sale_price', models.FloatField(verbose_name='Net Sale Price')),
                ('gross_sale_price', models.FloatField(verbose_name='Gross Sale Price')),
            ],
        ),
    ]
